baseURL = "https://blog.peterchen.xyz/"
languageCode = "en-us"
title = "Peter's Blog"
theme = "smol"
copyright = "Peter Chen"

[params]
    subtitle = "blog for everything"
    dateFmt = "01.02.2006 15:04"

    mainSections = ["tech", "dir1"]
[taxonomies]
    tag = "tags"
    categories = "categories"
    mood = "moods"
# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/advpetc"
        weight = 1 

    [[menu.footer]]
        name = "Imprint"
        url = "/imprint"
        weight = 3 